p8105_hw2_yl4610
================
Yuxin Liu
2022-10-01

\#question1

``` r
# load the libraries
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)
library(dplyr)
# Read and clean the data
NYCtransit_data = read_csv( "./datafiles/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>%
janitor::clean_names() %>% 
# retain certain variables
select(line, station_name, station_latitude, station_longitude, route1:route11, entry, exit_only, vending, entrance_type, ada) %>% 
# Convert the entry variable from character (YES vs NO) to a logical variable
mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

This dataset contains variables such as line, station_name,
station_latitude, station_longitude, route1, route2, route3, route4,
route5, route6, route7, route8, route9, route10, route11, entry,
exit_only, vending, entrance_type, ada. I used janitor to clean names,
select to include variables that I want, and mutate to convert the
character variable “entry” to logical variable.  
It contains 20 columns and 1868 rows. These data are not tidy because
route number should be a variable instead of having 11 columns of
different routes. I should convert `route` variables from wide to long
format. In this way, it is more convenient to check on specific routes
within one column.

``` r
NYCtransit_data %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

There are 465 distinct stations.

How many stations are ADA compliant?

``` r
NYCtransit_data %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

84 stations are ADA compliant.

``` r
NYCtransit_data %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

0.3770 or 37.70% station entrances / exits without vending allow
entrance

``` r
NYCtransit_data %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
NYCtransit_data %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

There are 60 distinct stations serve the A train. Of the stations that
serve the A train, 17 are ADA compliant.

\#question2 Mr. Trash Wheel dataset:

``` r
# Read and clean the data
MrTrash_data = read_excel(
  "./datafiles/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", 
# specify the sheet in the Excel file and to omit non-data entries
  sheet = 1,
  range = "A2:N534") %>%  
# use reasonable variable names
janitor::clean_names() %>%
# omit rows that do not include dumpster-specific data
drop_na(dumpster) %>% 
# round sports balls to nearest integer and converts it to an integer variable
mutate(sports_balls = round(sports_balls)) #%>%
#mutate(as.integer(sports_balls))
#add a variable
#mutate(dumpster = month.name[month])
```

Professor Trash Wheel dataset:

``` r
# Read and clean the data
ProfTrash_data = read_excel(
  "./datafiles/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", 
# specify the sheet in the Excel file and to omit non-data entries
  sheet = 2,
  range = "A2:N116") %>%  
# use reasonable variable names
janitor::clean_names() %>%
# omit rows that do not include dumpster-specific data
drop_na(dumpster) %>% 
#add a variable
mutate(dumpster = month.name[month])
```

``` r
#left_join(MrTrash_data, ProfTrash_data, by = "")
```

The total weight of trash collected by Professor Trash Wheel? The total
number of sports balls collected by Mr. Trash Wheel in 2020? \`r
nsum(ProfTrash_data, dumpster)

\#question3 clean the data in pols-month.csv

``` r
#read pols-month.csv
pols_month_data = read_csv( "./datafiles/fivethirtyeight_datasets/pols-month.csv") %>%
janitor::clean_names() %>% 
# break up the variable mon into integer variables
separate(mon, into = c("year", "month", "day")) %>% 
#  replace month number with month name
mutate(month = month.name[as.numeric(month)]) %>%
# create a president variable taking values gop and dem
mutate(president = prez_gop + prez_dem) %>%
# remove prez_dem and prez_gop; and remove the day variable
select(-prez_dem, -prez_gop, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

clean the data in snp.csv

``` r
#read snp.csv 
pols_month_data = read_csv( "./datafiles/fivethirtyeight_datasets/snp.csv") %>%
janitor::clean_names() %>% 
separate(date, into = c("month", "day", "year"))
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# reformat date

mutate(date = as.Date(as.character(date), format = “%d/%m/%y”)) \# break
up the variable date into integer variables separate(date, into =
c(“year”, “month”, “day”)) %\>% \# reformat date mutate(date =
month.name\[as.numeric(month)\]) %\>%

# remove the day variable

select(-day) %\>% \# organize so that year and month are the leading
columns relocate(“year”, “month”)
